### ISSUE TITLE
Redesign TFM (TFM 5.0)

### ISSUE THREAD

**Issue by JeromSar** [TotalFreedom/TotalFreedomMod#597]
I've long thought of this, and I think it's best if a large part of TFM is redesigned and re-implemented. A lot of the old code can be reused, but the semantics would change. Old issue: #369.

---
TotalFreedomMod has for a very long time been written using little to no instantiated objects. This, as it turns out, is a [bad practice](https://forums.bukkit.org/threads/how-to-make-your-plugin-better.77899/). It seems static references are not collected by the garbage collector. As a result of this, every time TFM reloads, the previously used memory isn't freed which results in a memory leak.

Switching TFM to a more instantiated design will improve performance and will doubtfully create a more modular project which can in terms be used to improve the project's coding standards.

---

To accomplish this, I'll start making commits on a new branch: `tfm50`. The commits on this branch will be unstable and likely untested, but open for peer review. Once all work is done and tested, the commits will be squashed into a single commit, and merged with master.

**TODO**
* [x] Use instantiated object instead of static references
* [x] Use [Aero](https://github.com/Pravian/Aero) for services and dynamic command loaders
* [x] Refractor to `me.totalfreedom.totalfreedommod`
* [x] Remove all `TFM_` prefixes.
* [x] Remove UUID system 
* [x] Retest all features
* [x] Clean up `FUtil.java` (#268)

**Comment by AlexFreedomMod** [comment]
@xDestroyer217 Why would @JeromSar Kill you just for one little spelling mistake?

**Comment by JeromSar** [comment]
@xDestroyer217 @AlexFreedomMod Whoops my bad, fixed. :)

**Comment by AlexFreedomMod** [comment]
@JeromSar On the first line I think you made a typo.

**Comment by Wild1145** [comment]
@AlexFreedomMod @JeromSar No, he was just talking about going to AA, its not a mistake :P </sarcasm>

**Comment by AlexFreedomMod** [comment]
Oh

**Comment by Wild1145** [comment]
@AlexFreedomMod Whoops, the comment trimmed my part off the end. It is a mistake, im just trolling a tad

**Comment by AlexFreedomMod** [comment]
Same with mine

**Comment by Scuph** [comment]
Great Idea! Finally updated the AdminList, Praise the lawd!

**Comment by PattyToTheWatty** [comment]
Bump. Is this still going to be implemented?

**Comment by JeromSar** [comment]
@PattyToTheWatty Yes.

**Comment by PattyToTheWatty** [comment]
Yay!

**Comment by OxLemonxO** [comment]
Done now
Should be closed

**Comment by StevenLawson** [comment]
Glad you're taking this on, @JeromSar. When I first started TFM I never really had an "end product" in mind, and things just kept getting slapped on layer after layer (e.g. initially, "superadmin" was only going to be Mark and I). At the time, I wasn't nearly as well versed in Java as I am now, and tried to use familiar patterns from other languages that ended up not being very efficient. So, yes, TFM does indeed need a new foundation.

**Comment by JeromSar** [comment]
Thanks @StevenLawson. I've created a non-functional base for TFM 5.0 here: https://github.com/TotalFreedom/TotalFreedomMod/tree/tfm50

Mind taking a peek, and tell me what you think?

**Comment by FoxIshDaBest** [comment]
@JeromSar may I ask, what was TFM_AdminList renamed to? I cannot find it ;-;

**Comment by AvalancheYT** [comment]
https://github.com/TotalFreedom/TotalFreedomMod/blob/tfm50/src/main/java/me/totalfreedom/totalfreedommod/admin/AdminList.java

If you want to add a player, it's ```plugin.al.isSuperAdmin(player);``` or something but that's a different story.

**Comment by FoxIshDaBest** [comment]
I need it for FreedomBot 2.1 @AvalancheYT.
